WIP: testing...

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -27,10 +27,24 @@ jobs:
       - uses: actions/setup-python@v2
       - run: pip install --upgrade tox
       - name: Run black code formatter (https://black.readthedocs.io/en/stable/)
-        run: tox -e black -- --check
+        run: |
+          if ! tox -e black -- --check; then
+            echo "ERROR: Black format check failed."
+            echo 'Run the following command to fix the error:'
+            echo "    tox -e black"
+            echo ""
+            false
+          fi
       - name: Run flake8 (https://flake8.pycqa.org/en/latest/)
         run: tox -e pep8
       - name: Run mypy static typing checker (http://mypy-lang.org/)
         run: tox -e mypy
       - name: Run isort import order checker (https://pycqa.github.io/isort/)
-        run: tox -e isort -- --check
+        run: |
+          if ! tox -e isort -- --check; then
+            echo "ERROR: isort format check failed."
+            echo 'Run the following command to fix the error:'
+            echo "    tox -e isort"
+            echo ""
+            false
+          fi
